export const selectCard = (state) => state.card
export const selectCardProducts = (state) => state.card.products
export const selectCards = (state) => state.cards
export const selectCommand = (state) => state.command
export const selectMenuVisibility = (state) => state.navigation.isMenuVisible
export const selectService = (state) => state.service
export const selectServiceCard = (state) => state.service.card
export const selectServiceCommands = (state) => state.service.commands
export const selectProducts = (state) => state.products
export const selectProduct = (state) => state.product